# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4be38c01fc31a96b68cff78ca802f94810b84d2e0e50bfc884a8f5df1c8e411a508d754e28710543fd92255a0cd3f33d0d2666dd5873ad06ad99d7098df765a2

test:
  secret_key_base: ada085fa5c8124d6c58d92d7b775dc2ab6823d6e540c53fe4e10d53ab27611beb992f273b74e71308663be196d5d6272908f80e0f6241e25cd15c92525c2f76d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
